name: example-environment
channels:
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - imagemagick
  - ipyleaflet
  - ipyvolume
  - pandas
  - pillow
  - pip
  - pip:
    - nbgitpuller
    - geopy
    - geojson
    - sidecar
  - python==3.8.1
  - voila
