name: example-environment
channels:
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  # - imagemagick
  - ipyleaflet
  - ipyvolume>=0.5.2
  - jupyterlab
  - pandas
  - pillow
  - pip
  - pip:
    - nbgitpuller
    - geopy
    - geojson
    - sidecar
  - python==3.7.6
  - voila
