#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install ipyvolume
jupyter labextension install jupyter-threejs

jupyter labextension install @jupyterlab/geojson-extension
