#!/bin/bash

jupyter labextension install \
    @jupyter-widgets/jupyterlab-manager \
    @jupyterlab/geojson-extension \
    @jupyter-voila/jupyterlab-preview \
    ipyvolume \
    jupyter-threejs \
    jupyter-leaflet

jupyter lab build
